import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { TopNav } from "@/components/nav/topnav";
import { Sidebar } from "@/components/nav/sidebar";
import { getSessionUser } from "@/lib/auth";
import { PageTransition } from "@/components/nav/page-transition";
import { TaskRegistryProvider } from "@/lib/jobs/client/task-registry";
import { LanguageProvider } from "@/lib/i18n/client";
import { getLocale } from "@/lib/i18n/get-locale";
import { ServiceWorkerRegistrar } from "@/components/pwa/service-worker";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: {
    default: "GBA · BBMP Ward & Engineer Tracker",
    template: "%s · GBA BBMP",
  },
  description:
    "Trace any Bengaluru locality across the 198 → 225 → 369 ward restructures and reach the responsible engineering sub-division.",
  icons: {
    icon: [
      { url: "/icon.svg?v=4", type: "image/svg+xml" },
      // PNG fallbacks generated by `npm run icons:gen`. Android's installed-app
      // and "add to home screen" paths take these from the manifest, but the
      // apple-touch-icon below has no manifest equivalent on iOS.
      { url: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icons/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: "/icons/icon-192.png",
  },
};

/**
 * Declaring this export replaces Next's default viewport tag, so width and
 * initialScale are restated verbatim rather than inherited. themeColor is what
 * tints the Android status bar in the installed app; it mirrors the manifest's
 * theme_color (app/manifest.ts), which is separately what Bubblewrap bakes into
 * the APK's splash screen.
 */
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#1e40af",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [user, locale] = await Promise.all([getSessionUser(), getLocale()]);

  return (
    <html lang={locale} className={inter.variable} suppressHydrationWarning>
      <body className="font-sans antialiased" suppressHydrationWarning>
        <a href="#main-content" className="skip-link">
          Skip to main content
        </a>
        <ServiceWorkerRegistrar />
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <LanguageProvider initialLocale={locale}>
            <TaskRegistryProvider>
              <div className="flex min-h-screen flex-col">
                <TopNav email={user?.email ?? null} role={user?.role ?? null} />
                <div className="flex flex-1">
                  <Sidebar />
                  <main
                    id="main-content"
                    className="min-w-0 flex-1 px-4 py-6 sm:px-6 lg:px-8 xl:px-10"
                  >
                    <PageTransition>{children}</PageTransition>
                  </main>
                </div>
              </div>
            </TaskRegistryProvider>
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
