"use client";

import * as React from "react";
import { PageHeader } from "@/components/page-header";
import { ChevronDown, ChevronUp } from "lucide-react";

export function ComplaintsSettingsHeader() {
  const [expanded, setExpanded] = React.useState(false);
  return (
    <>
      {/* Desktop Header */}
      <div className="hidden md:block">
        <PageHeader
          title="Complaint settings"
          description="Case-number prefix, follow-up rules, OCR language, AI auto-summary, and upload limits. Edits here affect all future complaints generated by the system."
        />
      </div>
      {/* Mobile Header */}
      <div className="block md:hidden bg-slate-50/50 dark:bg-slate-900/30 p-3.5 rounded-xl border border-slate-200 dark:border-slate-800 mb-4 space-y-1.5">
        <h1 className="text-xl font-bold tracking-tight text-slate-850 dark:text-slate-105">
          Complaint settings
        </h1>
        <div className="text-xs text-slate-550 dark:text-slate-400 leading-relaxed">
          {expanded ? (
            <p>
              Case-number prefix, follow-up rules, OCR language, AI auto-summary, and upload limits. Edits here affect all future complaints generated by the system.
            </p>
          ) : (
            <p className="line-clamp-2">
              Case-number prefix, follow-up rules, OCR language, AI auto-summary, and upload limits...
            </p>
          )}
          <button
            type="button"
            onClick={() => setExpanded(!expanded)}
            className="text-blue-600 hover:text-blue-700 font-bold mt-1 inline-flex items-center gap-0.5 cursor-pointer text-[11px]"
          >
            {expanded ? "Show Less" : "Read More"}
            {expanded ? <ChevronUp className="h-3.5 w-3.5" /> : <ChevronDown className="h-3.5 w-3.5" />}
          </button>
        </div>
      </div>
    </>
  );
}
